name: PATH/TO/CLONED/PROJECT/BASE/FOLDER/env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pandas
  - seaborn
  - onnx
  - pillow
  - numpy
  - onnxruntime
  - scikit-learn
  - pycocotools
  - onnx2torch
  - ipykernel
  - torchvision=0.13.1
  - h5py
  - tqdm
  - ipywidgets
  - av
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - tslearn
  - opencv
  - pytables
  - ffmpeg-python
prefix: PATH/TO/CLONED/PROJECT/BASE/FOLDER/env
